--- #YAML:1.0
name:                WWW-Mechanize-Plugin-JavaScript
version:             0.002
abstract:            JavaScript plugin for WWW::Mechanize
license:             ~
author:              
    - Father Chrysostomos <sprout & cpan . org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    CSS::DOM::Interface:           0
    Encode:                        0
    HTML::DOM:                     0.01
    HTML::DOM::Interface:          0
    HTTP::Headers::Util:           0
    JE:                            0.019
    LWP::Simple:                   0
    Scalar::Util:                  0
    strict:                        0
    Test::More:                    0
    Time::HiRes:                   0
    URI:                           0
    URI::file:                     0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
